### ISSUE TITLE
Improve error message when failed to insert on Cassandra

### ISSUE THREAD

**Issue by ebyhr** [trinodb/trino#417]
When we try to insert into cassandra type which isn't supported, the error message is like below. It would be better to throw user-friendly message.
```
Codec not found for requested operation: [uuid <-> java.lang.String]
```
```
2019-03-09T12:49:07.319+0545	ERROR	remote-task-callback-26	io.prestosql.execution.StageStateMachine	Stage 20190309_070407_00008_fzg8z.1 failed
com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [uuid <-> java.lang.String]
	at com.datastax.driver.core.CodecRegistry.notFound(CodecRegistry.java:679)
	at com.datastax.driver.core.CodecRegistry.createCodec(CodecRegistry.java:540)
	at com.datastax.driver.core.CodecRegistry.findCodec(CodecRegistry.java:520)
	at com.datastax.driver.core.CodecRegistry.codecFor(CodecRegistry.java:470)
	at com.datastax.driver.core.AbstractGettableByIndexData.codecFor(AbstractGettableByIndexData.java:77)
	at com.datastax.driver.core.BoundStatement.bind(BoundStatement.java:201)
	at com.datastax.driver.core.DefaultPreparedStatement.bind(DefaultPreparedStatement.java:126)
	at io.prestosql.plugin.cassandra.CassandraPageSink.appendPage(CassandraPageSink.java:120)
	at io.prestosql.operator.TableWriterOperator.addInput(TableWriterOperator.java:237)
	at io.prestosql.operator.Driver.processInternal(Driver.java:384)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1075)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:162)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:483)
	at io.prestosql.$gen.Presto_null__testversion____20190309_062202_1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hashhar** [comment]
Seems this is fixed since it now returns errors like below (if I remove the INTEGER writer from CassandraPageSink).

```
trino:tpch> create table foa (a integer, b boolean, c double);
CREATE TABLE
trino:tpch> insert into foa values (1, false, 1.0);
Query 20220304_213729_00005_zz9k4 failed: Unsupported column type: integer
```

**Comment by ebyhr** [comment]
This isn't fixed. We can reproduce with `varint` type without code change.
